import { ProjectItem } from './types';

export const INITIAL_PROJECTS: ProjectItem[] = [
  {
    id: '1',
    name: 'CHỈNH SỬA MÔ HÌNH NEWEB',
    subName: 'LICOGI13FC',
    priority: 1,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 55,
    completedTasks: '87/158',
    actualHours: '197.0/380h',
    weekReport: 'Tuần 32/2028',
    latestRemark: 'Thông báo điều chỉnh tiến độ dự án: Để đảm bảo lịch trình nghỉ mát cho toàn bộ nhân viên công ty, các phòng lưu ý tiến độ hoàn thành chỉnh sửa dự án sẽ được đẩy sớm lên 03 ngày làm việc. Theo đó: - Nghiệm thu 100%: 07/08/2028 - Vận chuyển, lắp đặt & Bàn giao mô hình: 08/08/2028 Em cảm ơn,',
  },
  {
    id: '2',
    name: 'QUY HOẠCH TỈNH HƯNG YÊN',
    subName: 'DATVIETGROUP',
    priority: 2,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 13,
    completedTasks: '47/351',
    actualHours: '377.0/2317h',
    weekReport: 'Tuần 31/2028',
    latestRemark: 'Kết luận sau cuộc họp A- Tiến độ tổng thể dự án: đảm bảo tiến độ B- Tình trạng thực tế & những vấn đề cần lưu ý: - Phòng Khai triển tập trung kiểm tra, tổng hợp hồ sơ dự án & hoàn thiện bộ hồ sơ xác nhận triển khai dự án trong tuần này. Lập bảng tiến độ chi tiết của phòng trong tuần này - Phòng CN&TK chuẩn bị kịch bản trình chiếu sơ bộ...',
  },
  {
    id: '3',
    name: 'KIÊN GIANG MASTER PLAN PROJECT MODEL',
    subName: 'CÔNG TY TNHH DAEWOO ENGINEERING & CONSTRUCTION VIỆT NAM',
    priority: 3,
    status: 'Đang thực hiện',
    evaluation: 'Chưa đánh giá',
    progressPct: 1,
    completedTasks: '5/385',
    actualHours: '31.0/2404h',
    weekReport: null,
  },
  {
    id: '4',
    name: 'PHÒNG HỌP MHV',
    subName: 'MHV',
    priority: 4,
    status: 'Đang thực hiện',
    evaluation: 'Chưa đánh giá',
    progressPct: 48,
    completedTasks: '30/62',
    actualHours: '85.5/307h',
    weekReport: null,
  },
  {
    id: '5',
    name: 'QUÀ TẶNG KHÁCH HÀNG',
    subName: 'MHV',
    priority: 5,
    status: 'Đang thực hiện',
    evaluation: 'Chưa đánh giá',
    progressPct: 46,
    completedTasks: '30/65',
    actualHours: '140.0/388h',
    weekReport: null,
  },
  {
    id: '6',
    name: 'THE HERITAGE TÂY NINH - Lắp đặt tại Tây Ninh',
    subName: 'The Heritage Tây Ninh',
    priority: 6,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 78,
    completedTasks: '357/459',
    actualHours: '2293.5/2838h',
    weekReport: 'Tuần 31/2028',
    latestRemark: 'A- Tiến độ tổng thể dự án: đảm bảo tiến độ B1- Tình trạng thực tế & những vấn đề cần lưu ý: - Các phòng tiếp tục thực hiện hoàn thiện mô hình thứ 2 - Lưu ý các hạng mục cần phải điều chỉnh từ mô hình thứ nhất sẽ phải được cập nhật đầy đủ sang mô hình thứ 2 B2- Mục tiêu công việc tuần kế tiếp của dự án: + Tiếp tục triển khai khối lượng có...',
  },
  {
    id: '7',
    name: 'THE HERITAGE TÂY NINH - Lắp đặt tại Hà Nội',
    subName: 'The Heritage Tây Ninh',
    priority: 7,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 85,
    completedTasks: '472/553',
    actualHours: '3277.3/3454h',
    weekReport: 'Tuần 31/2028',
    latestRemark: 'A- Tiến độ tổng thể dự án: đảm bảo tiến độ B1- Tình trạng thực tế & những vấn đề cần lưu ý: - Các phòng tiếp tục thực hiện hoàn thiện & điều chỉnh các hạng mục không cần chờ thông tin xác nhận của khách hàng bao gồm: + Cảnh quan khu công viên trải nghiệm + Cảnh quan tuyến phố đi bộ + Cảnh quan khu clubhouse + Điều chỉnh màu sắc s...',
  },
  {
    id: '8',
    name: 'Dự án IA25 -CIPUTRA',
    subName: 'IA25 -CIPUTRA',
    priority: 8,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 55,
    completedTasks: '305/553',
    actualHours: '2035.5/3495h',
    weekReport: 'Tuần 31/2028',
    latestRemark: 'Kết luận sau cuộc họp A- Tiến độ tổng thể dự án: - Phòng Điện & Phòng Cảnh quan tiếp tục thực hiện phần chuẩn bị ô tô & cây cho mô hình - Các phòng còn lại tiếp tục dừng triển khai mô hình B- Tình trạng thực tế & những vấn đề cần lưu ý: - Ngày 07/07/2028: khách hàng xác nhận 02 nội dung: + Nội dung liên quan đến hình ảnh & tên của hàng...',
  },
  {
    id: '9',
    name: 'VSIP LẠNG SƠN',
    subName: 'VSIP Lạng Sơn',
    priority: null,
    status: 'Đang thực hiện',
    evaluation: 'Vượt tiến độ',
    progressPct: 99,
    completedTasks: '473/478',
    actualHours: '2630.1/2638h',
    weekReport: null,
  },
  {
    id: '10',
    name: '22 LIỄU GIAI',
    subName: 'CĐT 22 LIỄU GIAI',
    priority: null,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 89,
    completedTasks: '484/521',
    actualHours: '3075.8/2944h',
    weekReport: 'Tuần 31/2028',
    latestRemark: '1- Đánh giá tiến độ tổng thể của dự án: đạt tiến độ 2- Những vấn đề cần lưu ý: - Mô hình đã hoàn thành 100% - Văn phòng trưng bày chưa sẵn sàng để nhận bàn giao mô hình. Thời gian vận chuyển & bàn giao mô hình sẽ được phụ trách KD thông báo sau 3- Các mốc thời gian quan trọng - Lịch vận chuyển dự kiến: đầu tháng 8/2028',
  },
  {
    id: '11',
    name: 'CHỈNH SỬA MÔ HÌNH L\'AURORA',
    subName: 'CĐT L\'AURORA',
    priority: null,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 94,
    completedTasks: '317/338',
    actualHours: '1846.5/1704h',
    weekReport: 'Tuần 31/2028',
    latestRemark: '1- Đánh giá tiến độ tổng thể của dự án: đạt tiến độ 2- Những vấn đề cần lưu ý: - Các phòng đã hoàn thành các phần chính sửa theo Biên bản nghiệm thu ngày 21/07/2028 - Đối với hạng mục bổ sung thêm clubhouse: thời gian kết thúc dự kiến là ngày 01/08/2028 3- Các mốc thời gian quan trọng - Nghiệm thu siêu cuối: 03/08/2028',
  },
  {
    id: '12',
    name: 'HERITAGE VILLAGE MỘC CHÂU',
    subName: 'HERITAGE VILLAGE MỘC CHÂU',
    priority: null,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 89,
    completedTasks: '455/514',
    actualHours: '2157.0/2260h',
    weekReport: null,
  },
  {
    id: '13',
    name: 'BÁO CÁO NGOÀI DỰ ÁN',
    subName: '-',
    priority: null,
    status: 'Đang thực hiện',
    evaluation: 'Đúng tiến độ',
    progressPct: 54,
    completedTasks: '96/179',
    actualHours: '746.0/859h',
    weekReport: null,
  },
];
